include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
      - helm-ci.yml
      - sonar-ci.yml
    ref: main

default:
  image: alpine:3.23
variables:
  REGISTRY_URL: ${REGISTRY_HOST}/${PROJECT_PATH}
  CHARTS_DIR: ./charts

stages:
  - read-secret
  - check-quality
  - docker-build
  - helm-package

read_secret:
  stage: read-secret
  extends: .vault:read_secret

sonarqube:
  variables:
    SONAR_PROJECT_KEY: ${PROJECT_KEY}
  stage: check-quality
  extends: .sonar:sonar-scanner
  allow_failure: true

docker-build-client:
  stage: docker-build
  extends: .kaniko:build-push
  variables:
    WORKING_DIR: ./apps/client
    DOCKERFILE: ./apps/client/Dockerfile
    IMAGE_NAMES: ""  # Overridden in before_script
  before_script:
    - |
      SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-7)
      TAGS="client:$SHORT_SHA"
      if [ "$CI_COMMIT_REF_NAME" != "main" ]; then
        TAGS="$TAGS client:$CI_COMMIT_REF_SLUG"
      fi
      if [ -n "$CI_COMMIT_TAG" ]; then
        TAG_WITHOUT_V=${CI_COMMIT_TAG#v}
        TAGS="$TAGS client:$TAG_WITHOUT_V"
        if echo "$CI_COMMIT_TAG" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
          TAGS="$TAGS client:latest"
        fi
      fi
      export IMAGE_NAMES="$TAGS"
      echo "Building with tags: $IMAGE_NAMES"

docker-build-server:
  stage: docker-build
  extends: .kaniko:build-push
  variables:
    WORKING_DIR: ./apps/server
    DOCKERFILE: ./apps/server/Dockerfile
    IMAGE_NAMES: ""  # Overridden in before_script
  before_script:
    - |
      SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-7)
      TAGS="server:$SHORT_SHA"
      if [ "$CI_COMMIT_REF_NAME" != "main" ]; then
        TAGS="$TAGS server:$CI_COMMIT_REF_SLUG"
      fi
      if [ -n "$CI_COMMIT_TAG" ]; then
        TAG_WITHOUT_V=${CI_COMMIT_TAG#v}
        TAGS="$TAGS server:$TAG_WITHOUT_V"
        if echo "$CI_COMMIT_TAG" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
          TAGS="$TAGS server:latest"
        fi
      fi
      export IMAGE_NAMES="$TAGS"
      echo "Building with tags: $IMAGE_NAMES"

.helm-package-push: # Remove `.` at the start of the job if helm-package-push is enabled (for monorepo including charts)
  stage: helm-package
  extends: .helm:build-push
  only:
    - tags
    - main
  image: alpine/helm:4.1.3
