{{- if or .Values.server.envCm .Values.global.envCm -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "server" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "server")) | nindent 4 }}
data:
  {{- if .Values.global.envCm -}}
  {{- include "helper.env" .Values.global.envCm | indent 2 }}
  {{- end -}}
  {{- if .Values.server.envCm -}}
  {{- include "helper.env" .Values.server.envCm | indent 2 }}
  {{- end -}}
{{- end -}}
