services:
  server:
    image: test-app/server:prod
    container_name: test-app_server
    build:
      context: ../apps/server
      dockerfile: ./Dockerfile
      target: prod
    restart: always
    ports:
      - 8081:8081
    networks:
      - test-app-network

  client:
    image: test-app/client:prod
    container_name: test-app_client
    build:
      context: ../apps/client
      dockerfile: ./Dockerfile
      target: prod
    restart: always
    ports:
      - 8080:8080
    environment:
      VITE_API_URL: http://localhost:8081/api
    networks:
      - test-app-network

networks:
  test-app-network:
    driver: bridge