apiVersion: v2
name: test-app
type: application
version: 0.2.7
appVersion: 0.2.1
description: A Helm chart to deploy test-app.
# home: https://this-is-tobi.com
deprecated: false
annotations: {}
keywords: []
dependencies: []
# - name: keycloak
#   version: ">=21.4.1"
#   repository: https://charts.bitnami.com/bitnami
#   condition: keycloak.enabled
sources: []
# - https://github.com/this-is-tobi/helm-charts
maintainers: []
# - name: this-is-tobi
#   email: this-is-tobi@proton.me
#   url: https://this-is-tobi.com
